//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BertoniServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BertoniServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;userId&quot;: 1,
        ///    &quot;id&quot;: 1,
        ///    &quot;title&quot;: &quot;quidem molestiae enim&quot;
        ///  },
        ///  {
        ///    &quot;userId&quot;: 1,
        ///    &quot;id&quot;: 2,
        ///    &quot;title&quot;: &quot;sunt qui excepturi placeat culpa&quot;
        ///  },
        ///  {
        ///    &quot;userId&quot;: 1,
        ///    &quot;id&quot;: 3,
        ///    &quot;title&quot;: &quot;omnis laborum odio&quot;
        ///  },
        ///  {
        ///    &quot;userId&quot;: 1,
        ///    &quot;id&quot;: 4,
        ///    &quot;title&quot;: &quot;non esse culpa molestiae omnis sed optio&quot;
        ///  },
        ///  {
        ///    &quot;userId&quot;: 1,
        ///    &quot;id&quot;: 5,
        ///    &quot;title&quot;: &quot;eaque aut omnis a&quot;
        ///  },
        ///  {
        ///    &quot;userId&quot;: 1,
        ///    &quot;id&quot;: 6,
        ///    &quot;title&quot;: &quot;natus impedit quibusdam illo est&quot;
        ///  },
        ///  {
        ///    &quot;userId&quot;: 1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;postId&quot;: 1,
        ///    &quot;id&quot;: 1,
        ///    &quot;name&quot;: &quot;id labore ex et quam laborum&quot;,
        ///    &quot;email&quot;: &quot;Eliseo@gardner.biz&quot;,
        ///    &quot;body&quot;: &quot;laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium&quot;
        ///  },
        ///  {
        ///    &quot;postId&quot;: 1,
        ///    &quot;id&quot;: 2,
        ///    &quot;name&quot;: &quot;quo vero reiciendis velit similique earum&quot;,
        ///    &quot;email&quot;: &quot;Jayne_Kuhic@sydney.com&quot;,
        ///    &quot;body&quot;: &quot;est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;albumId&quot;: 1,
        ///    &quot;id&quot;: 1,
        ///    &quot;title&quot;: &quot;accusamus beatae ad facilis cum similique qui sunt&quot;,
        ///    &quot;url&quot;: &quot;http://placehold.it/600/92c952&quot;,
        ///    &quot;thumbnailUrl&quot;: &quot;http://placehold.it/150/92c952&quot;
        ///  },
        ///  {
        ///    &quot;albumId&quot;: 1,
        ///    &quot;id&quot;: 2,
        ///    &quot;title&quot;: &quot;reprehenderit est deserunt velit ipsam&quot;,
        ///    &quot;url&quot;: &quot;http://placehold.it/600/771796&quot;,
        ///    &quot;thumbnailUrl&quot;: &quot;http://placehold.it/150/771796&quot;
        ///  },
        ///  {
        ///    &quot;albumId&quot;: 1,
        ///    &quot;id&quot;: 3,
        ///    &quot;title&quot;: &quot;officia porro iure quia iusto qui ipsa ut modi&quot;,
        ///    &quot;url&quot;: &quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;userId&quot;: 1
        ///  },
        ///  {
        ///    &quot;userId&quot;: 2
        ///  },
        ///  {
        ///    &quot;userId&quot;: 3
        ///  },
        ///  {
        ///    &quot;userId&quot;: 4
        ///  },
        ///  {
        ///    &quot;userId&quot;: 5
        ///  },
        ///  {
        ///    &quot;userId&quot;: 6
        ///  },
        ///  {
        ///    &quot;userId&quot;: 7
        ///  },
        ///  {
        ///    &quot;userId&quot;: 8
        ///  },
        ///  {
        ///    &quot;userId&quot;: 9
        ///  },
        ///  {
        ///    &quot;userId&quot;: 10
        ///  }
        ///]
        ///.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
